### PR TITLE
fileContent is undefined

### PR DESCRIPTION
**Pull request by jnsdls**
needed to make it a var.

### CODE REVIEW

**Comment by jnsdls** [comment]
without this change this happens:

```
fileContent = ejs.render(templateContent, self.options);
              ^

ReferenceError: fileContent is not defined
    at VersionFile.writeFile ([...]/node_modules/webpack-version-file-plugin/index.js:65:15)
    at [...]/node_modules/webpack-version-file-plugin/index.js:54:12
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
```

**Comment by jnsdls** [comment]
@mvanede lmk if u need anything else, would be nice to get this merged quickly as the latest release is broken currently.

**Comment by jnsdls** [comment]
(also I just tested it by installing it from my test branch and it runs again) :)

**Comment by mvanede** [comment]
Tnxs!

**Pull request merged**
